name: Weekly Dynamic Seeds

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: "3.10" }
      - name: Install deps
        run: |
          pip install pytrends beautifulsoup4 requests pandas \
                      gspread google-auth google-auth-oauthlib google-api-python-client
      - name: Write creds.json from base64
        run: |
          echo "\${{ secrets.GOOGLE_CREDENTIALS_JSON }}" | base64 --decode > credentials.json
      - name: Run dynamic seeds
        env:
          SPREADSHEET_ID: \${{ secrets.SPREADSHEET_ID }}
        run: python dynamic_seeds.py
